name: task-a ci

on: [pull_request]

jobs:
  test:
    runs-on: "ubuntu-latest"
    name: pytest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'

        - name: Install dependencies
          run: |
            pip install -r ./task_a/requirements.txt

        - name: Run tests and generate report
          run: |
            pytest ./task_a/task_a.py --html=report.html

        - name: Upload test report
          uses: actions/upload-artifact@v4
          with:
            name: pytest-report
            path: report.html